version: '1'

services:
  CrocobetMongoDB:
    image: mongo:latest
    container_name: crocobet-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: crocobet_db
    volumes:
      - mongo_data_master:/data/db

volumes:
  mongo_data_master:
